#!/usr/bin/env python3
"""
generate_audio.py
Generates the dial tone, busy signal, and SIT PCM buffers — plus a sine lookup
table — as a C header file.
Output: src/c/touch_tone_audio.h

Format: 8kHz, 16-bit signed mono PCM. Buffers are 800 samples (~100 ms); larger
buffers queue several copies ahead, eliminating the underrun gaps that made
shorter buffers sound choppy.

Note: the 12 DTMF keypad tones are NOT pre-computed here. They are synthesized in
real time on-device from a phase accumulator + the SINE_TABLE below, which avoids
the loop-boundary discontinuity a repeated non-harmonic buffer would produce.
"""

import numpy as np

SAMPLE_RATE = 8000
BUFFER_SAMPLES = 800
AMPLITUDE = 0.8   # Leave headroom for two-tone mix

DIAL_TONE_FREQS = (350, 440)
BUSY_TONE_FREQS = (480, 620)   # US busy signal (Precise Tone Plan)
SIT_FREQS = [950, 1400, 1800]  # Special Information Tone (single tones, ascending)

SINE_TABLE_SIZE = 256          # entries in the real-time synth lookup table

# DTMF keypad frequencies are no longer emitted as buffers — they are synthesized
# on-device from SINE_TABLE. The pairs live in main.c (DTMF_FREQS) where the
# per-key phase increments are computed at startup.


def make_buffer(freqs):
    t = np.arange(BUFFER_SAMPLES) / SAMPLE_RATE
    wave = sum(np.sin(2 * np.pi * f * t) for f in freqs)
    wave /= len(freqs)          # normalize
    wave *= AMPLITUDE
    # Convert to int16 — clip to be safe
    samples = np.clip(wave * 32767, -32768, 32767).astype(np.int16)
    return samples


def fmt_array(name, samples):
    hex_vals = ", ".join(f"0x{int(s) & 0xFFFF:04X}" for s in samples)
    return (
        f"static const int16_t {name}[{len(samples)}] = {{\n"
        f"  {hex_vals}\n"
        f"}};\n"
    )


lines = [
    "/* AUTO-GENERATED by tools/generate_audio.py — DO NOT EDIT */",
    "/* 8kHz 16-bit signed mono PCM, 800 samples per buffer (~100ms) */",
    "#pragma once",
    "#include <stdint.h>",
    f"#define TONE_BUFFER_SAMPLES {BUFFER_SAMPLES}",
    f"#define SINE_TABLE_SIZE {SINE_TABLE_SIZE}",
    "",
]

# Generate dial tone buffer
dial_samples = make_buffer(DIAL_TONE_FREQS)
lines.append(f"/* Dial tone: {DIAL_TONE_FREQS[0]} Hz + {DIAL_TONE_FREQS[1]} Hz */")
lines.append(fmt_array("g_dial_tone", dial_samples))

# Busy signal: the cadence (0.5s on / 0.5s off) is built at runtime by
# alternating these two buffers. Both are TONE_BUFFER_SAMPLES (800) long, so
# 4000 samples = 0.5s = exactly 5 buffers per phase.
busy_on = make_buffer(BUSY_TONE_FREQS)
lines.append(f"/* Busy signal ON: {BUSY_TONE_FREQS[0]} Hz + {BUSY_TONE_FREQS[1]} Hz */")
lines.append(fmt_array("g_busy_tone_on", busy_on))

busy_silence = np.zeros(BUFFER_SAMPLES, dtype=np.int16)
lines.append("/* Busy signal OFF: true silence (zero-amplitude samples) */")
lines.append(fmt_array("g_busy_silence", busy_silence))

# SIT (Special Information Tone): three single-frequency tones, played in
# sequence with brief gaps at runtime. Each is a pure sine (one frequency, not
# a dual-tone mix). The 30ms gaps reuse g_busy_silence above.
for f in SIT_FREQS:
    sit = make_buffer([f])
    lines.append(f"/* SIT tone: {f} Hz (pure sine) */")
    lines.append(fmt_array(f"g_sit_{f}", sit))

# Sine lookup table for real-time DTMF synthesis: one full cycle of
# sin(2*pi*i/SINE_TABLE_SIZE) scaled to int16, indexed by the top 8 bits of a
# 32-bit phase accumulator.
sine = np.rint(np.sin(2 * np.pi * np.arange(SINE_TABLE_SIZE) / SINE_TABLE_SIZE) * 32767)
sine = np.clip(sine, -32768, 32767).astype(np.int16)
lines.append("/* One cycle of sine, int16 — for the real-time DTMF phase-accumulator synth */")
lines.append(fmt_array("SINE_TABLE", sine))
lines.append("")

output = "\n".join(lines)
with open("src/c/touch_tone_audio.h", "w") as f:
    f.write(output)
print("Wrote src/c/touch_tone_audio.h")
